### PR TITLE
Training

### PR DESCRIPTION
**Pull request by kheyer**
I added scripts for users to retrain the model if they so desire. I also did a decent bit of folder reorganizing. I've tested things locally and they all seem to work fine, but maybe you can try run the data download script and see if you can initiate training with the train model script.

There's one specific issue I need some help with. When I was moving folders around, I accidentally committed a model that I needed in my local directory but didn't want in the repo itself. I removed the file, but it appears to still be in the `.git/objects/pack` directory that is downloaded when you clone the repo. So effectively there's still a huge unnecessary file hanging around. How do I remove this?

### CODE REVIEW

**Comment by zhampel** [comment]
Hey @kheyer I'll test out your scripts sometime this evening, as I'll be driving down south soon. To answer your question about the extra-large file, as a band-aid, you can simply add it to your .gitignore file for now. We can go through the right steps in git later to get rid of it, if it remains later.

**Review by zhampel — COMMENTED** [review]
Hey @kheyer I've tried running cmd line inference but have run into a streamlit issue. Have you seen this before:

```
(deep_synthesis) zhampel on gpu11 in Deep-Synthesis
$ python Synthesis/translate_cli.py --runtime local --source_file data/source_small.txt --destination_file data/prediction_outputs.csv --target_file data/target_small.txt
[20:04:34] WARNING: not removing hydrogen atom without neighbors
[20:04:34] WARNING: not removing hydrogen atom without neighbors
[20:04:34] WARNING: not removing hydrogen atom without neighbors
[20:04:34] WARNING: not removing hydrogen atom without neighbors
[20:04:34] WARNING: not removing hydrogen atom without neighbors
Traceback (most recent call last):
  File "Synthesis/translate_cli.py", line 51, in <module>
    prediction = translate_data(data, int(args.beam), int(args.n_best), False, translator_class, model_description)
  File "/home/zhampel/Insight/kheyer/Deep-Synthesis/Synthesis/confirm_button.py", line 55, in wrapped_func
    raise st.ScriptRunner.StopException
AttributeError: module 'streamlit' has no attribute 'ScriptRunner'
```

**Comment by zhampel** [comment]
I'm following your `build_local/buildEnv.sh` instructions.

**Comment by kheyer** [comment]
Good catch. I think that's Streamlit complaining that there's no actual Streamlit session running for the CLI script.

I just pushed a new version that doesn't use the translation function designed for Streamlit in the CLI script. I was able to reproduce the error on my machine and fix the error with the changes.

Other than that, did you run into any issues during setup?

**Comment by zhampel** [comment]
I haven't run into any other problems setting up, running inference nor training. I haven't let it train for a full 3 days, however ;) Is there an easy way to parallelize the training process from cmd line? I see that `gpu_ranks` is used as an identifier, but I've got 4 GPUs, so this would speed up the training significantly ;)

**Comment by kheyer** [comment]
OpenNMT has their own code for parallelizing training. I've never used it as I only have 1 GPU, but it should be as simple as changing the last section of the `molecular_transformer.yml` file.

Change 

    gpu_ranks:
    - 0

to 

    world_size: 4
    gpu_ranks:
    - 0
    - 1
    - 2
    - 3

And fingers crossed it should just work. You might need to update the batch size - I don't know if it automatically scales the provided batch size across all GPUs.

**Comment by zhampel** [comment]
@kheyer yes! After adding the world size and extra GPU ranks, looks like training on 4GPUs works :)

**Comment by zhampel** [comment]
@kheyer I'm gonna let this run for a while but in case my ssh times out (I'm working remotely this week), I can give you a snap shot of the time so far w/4 GPUs. To reach 2000 steps, it's taken 24.5 min, going from 26.10% accuracy to 73.47% in that time. I provide a full print out of the training so far to see if it has accelerated training to your expectations.

[deep_synthesis_training_4GPUs.txt](https://github.com/kheyer/Deep-Synthesis/files/3703604/deep_synthesis_training_4GPUs.txt)

**Comment by zhampel** [comment]
@kheyer I think you've got a solid codebase here, I have no further comments based on testing out the procedures you've outlined in good documentation. Is there anything specific you'd like me to test or look at? And did you solve your large model file issue? I don't see any additions to gitignore.

**Comment by zhampel** [comment]
@kheyer One other thing, I recommend you add a link to your demo slides somewhere near the top of your repo README, that way that's included in the documentation.

**Comment by zhampel** [comment]
Latest training info:
```
[2019-10-08 13:38:21,978 INFO] Step 20900/500000; acc:  99.51; ppl:  1.01; xent: 0.01; lr: 0.00086; 230335/130904 tok/s;  15504 sec
[2019-10-08 13:39:35,453 INFO] Step 21000/500000; acc:  99.51; ppl:  1.01; xent: 0.01; lr: 0.00086; 231246/129987 tok/s;  15577 sec
```

**Comment by kheyer** [comment]
That training trajectory looks correct. I'm going to go ahead and merge the training branch.

The large model file seems to still be lurking in the `/.git/objects` directory. I was working with another fellow to try squash the commits that added and deleted the model, but we didn't get it to work. I think the problem was we were tinkering on another branch while this branch `training` was still in existence. After this merge I'm going to prune some old branches and try again then.

For further testing, I'm working on some updates for the front end aimed at improving usability. Once that goes live I'd like to get your opinion on it.

**Pull request merged**
