### PR TITLE
Main setup branch

### PR DESCRIPTION
**Pull request by kheyer**
Hey Zig,

So I made a number of updates to how installation works. The model URL is now public, so no credentials are required to download it. A single shell script now sets up the conda environment, pulls in all dependencies and downloads the model.

This should work out of the box for running on a local machine.

### CODE REVIEW

**Comment by zhampel** [comment]
Ok, I'll try everything out when I get some time this afternoon!

**Comment by zhampel** [comment]
I went through the install process without a problem. Nice job consolidating everything.

Now I'm able to open the Streamlit dashboard you've made and things look reproducible.
However, on my linux box, I get the following callback message when running `streamiest run Synthesis/app.py`:
```
Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f7cfdf71598>)
Traceback (most recent call last):
  File "/home/zhampel/anaconda3/envs/deep_synthesis/lib/python3.6/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/home/zhampel/anaconda3/envs/deep_synthesis/lib/python3.6/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/zhampel/anaconda3/envs/deep_synthesis/lib/python3.6/site-packages/streamlit/bootstrap.py", line 95, in maybe_open_browser
    util.open_browser(Report.get_url(addr))
  File "/home/zhampel/anaconda3/envs/deep_synthesis/lib/python3.6/site-packages/streamlit/util.py", line 269, in open_browser
    subprocess.Popen(cmd, stdout=devnull, stderr=subprocess.STDOUT)
  File "/home/zhampel/anaconda3/envs/deep_synthesis/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/zhampel/anaconda3/envs/deep_synthesis/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xdg-open': 'xdg-open'
```
Again, I see the results working just fine on the browser itself, so that doesn't seem to be an actual issue, but perhaps there's something in there that helps you debug if necessary. So far, looks like a really cool implementation. Anything specific I can assist in reviewing for you?

Also, you have two stray tick marks in the README lines here:
```
source activate deep_synthesis`
streamlit run Synthesis/app.py`
```

**Comment by kheyer** [comment]
Interesting. It looks like xdg-utils are a set of command line tools. Maybe something on the Streamlit back end is calling that. I'll reach out to the Streamlit team.

I don't have any specific code concerns at the moment, the pipeline is working well for local predictions. In terms of documentation, am I commenting the code sufficiently?

If nothing else jumps out to you, I think we should merge into Master.

**Review by zhampel — APPROVED** [review]
Yes, I think that your commenting is sufficient for the time being. As the codebase crystalizes, it will be worth some more specifics, but in the meantime you're still iterating so go ahead and merge to take the next steps!

**Pull request merged**
