### PR TITLE
AWS Lambda Setup

### PR DESCRIPTION
**Pull request by kheyer**
Hey Zig,

This is a pull request to bring in all the code based around setting up an AWS Lambda function for inference and calling that function from the Streamlit app.

Major Changes:

`/lambda_setup` directory - this directory contains all the code required to set up inference on AWS Lambda. This includes code to create a Lambda layer for the dependencies. Instructions for actually doing this are in the readme of the directory.

`translate_aws.py` and `lambda_async.py` - these two python files contain functions to connect to AWS Lambda to run inference. `translate_aws.py` contains a class designed to handle preprocessing data for sending to AWS Lambda and processing inference outputs into the same form you would get running local prediction. `lambda_async.py` has some functions that allow for invoking Lambda functions concurrently for some extra prediction speed.

Requests for feedback:

On handling both local predictions and AWS predictions:

When I was rewriting things to work with predicting on AWS Lambda, I wanted to do things in such a way that local prediction was still possible for anyone interested in setting this up at home. I built things in such a way that different translation files (`translate.py` vs `translate_aws.py` can be swapped out easily. An interesting thing that came out of this is that prediction with AWS does not require OpenNMT to be cloned into the directory running the app, as all the translation dependencies are packaged with the AWS Lambda function. Taking advantage of this, I added an argparse system to `app.py`, where running `streamlit run Synthesis/app.py local` imports OpenNMT for translation, while running `streamlit run Synthesis/app.py AWS` does not. This works, but it feels clunky to have conditional imports based on a command line argument. Is there a better way to do this?

On downloading model files for local deployment vs AWS Lambda setup:

For running inference locally, the setup script `buildEnv.sh` runs `python build/download_model.py` to create a `/models` directory and download the trained model to that location. For setting up AWS Lambda, I added an almost identical copy of `download_model.py` designed to download the model to the relevant folder for creating a Lambda function. I thought about using a single function that would take a command line argument for the destination folder. Ultimately I decided against this because I preferred to have all scripts required to set up AWS Lambda contained in a single directory. What are your thoughts on this?

On code attribution:

Setting up a Pytorch model on AWS Lambda is surprisingly hard, and I had to use a lot of code written by others for the same task. I wanted to make sure I was properly attributing code. The code in `lambda_async.py` was taken from [this gist](https://gist.github.com/byrro/439d233636ac6894f87c1df6ff1fa298), and I added the attribution requested by the author to the python file. Several files in the `/lambda_setup` directory are taken from [this repo](https://github.com/mattmcclean/sam-pytorch-example). I include the repo link in the relevant files and link to it in the README in the `/lambda_setup` directory. Is this sufficient for attribution?

### CODE REVIEW

**Comment by zhampel** [comment]
One thing you can consider doing for the two `translate*` scripts is simply import both, and use the input string (AWS vs local) to call a predefined dictionary that simply assigns the class / functions you want. I suppose you'd have to define the respective `translate_data` functions under LambdaInterface / TranslationModel classes, but you can simply assign a out-of-class function based on that too. Something like:

```
...
from translate import *
from translate_aws import *

# Dictionary of configuration files
config_json_opts = {
                      'AWS' : 'configs/aws_description.json',
                      'local' : 'configs/model_description.json'
                   }

# Dictionary of translation classes
class_dict = {
                'AWS' : LambdaInterface,
                'local' : TranslationModel
             }

runtime = args.runtime

# Load appropriate model
model_description = json.load(open(config_json_opts[runtime]))

# Use appropriate class
trans_inst = class_dict[runtime]
translate_data = trans_inst.translate_data

...
```

I think something like this will work best. It is also better practice to use dictionaries in this way because it's more extensible, not needing to hardcode functions, but instead options to the dictionaries.

**Comment by zhampel** [comment]
For attribution, I looked at your comments and additions to the README and I think that's sufficient. So long as there is a clear indication of authorship and links to code/pages if they exist, that's fine. You've labelled everything clearly enough that you're not trying to misrepresent it.

**Comment by zhampel** [comment]
For your question/concern about local directories, one think you might consider is making a `definitions.py` file defines the repo's directory as it's being used. Something like this:

```
import os

# Local directory of Deep-Synthesis
DEEP_SYNTH_DIR = os.path.dirname(os.path.abspath(__file__))
```

This variable `DEEP_SYNTH_DIR` can then be used in any script in which `from definitions import *` is called. Does that help?

**Comment by kheyer** [comment]
I like the dictionary approach, I'll implement that. I also like the idea of putting the `translate_data` function within the class running it.

 I'm not sure about importing both functions though. The reason is if I'm not using the `TranslationModel` class, I don't need all the OpenNMT dependencies. This comes into play for the next step of all this where I'm going to serve the Streamlit front end from a docker container or something similar. In that scenario, all inference will be run on AWS Lambda, so the actual Streamlit front end instance doesn't need any of the OpenNMT files. I'd prefer to avoid bringing along a large amount of unnecessary files. Maybe a simple solution is to import both and add a `try, except` block to the OpenNMT imports.

**Comment by zhampel** [comment]
I suppose one can have import statements in specific classes, but I also don't know if all those unnecessary files will actually cause an overhead issue. They may not get called or loaded, or maybe there's a way to request not loading until a specific run time request, I don't know. A `try, except` may work as you suggest.

**Comment by kheyer** [comment]
Alright I've made some changes. 

For the two translation classes, I wasn't able to put the translation function within the class (ie `translator.translate_data`) due to issues with Streamlit caching the output predictions. It seems the translator needs to be instantiated within the `translate_data` function for caching to work properly.

What I did instead was unify the API between the two translation classes, so they both pass through the same `translate_data` function.

I've also made some updates to interfacing with AWS Lambda. For running inference in AWS mode, the app now pings the Lambda function on start to warm up the function so the user doesn't experience warmup delay when they initiate a prediction. This cuts a good 20-30 seconds off the prediction time.

I also added a docker file for building the repo in a container.

**Comment by zhampel** [comment]
Nice work @kheyer Is there anything I can specifically look at for you in a short time scale over the next couple of days? I just want to make sure that any pain points are directly addressed prior to a more global overview.

**Comment by kheyer** [comment]
Code-wise I think everything is working well at this stage. The main pain points lately have been AWS related. I'm going to go ahead and merge this branch.

In the next day or two, I'm going to be getting into unknown coding territory writing up tests. I'll let you know how that goes and if I need any help.

**Review by zhampel — APPROVED** [review]
Merge-able in current state. Please include further annotations / comments prior to final version.

**Pull request merged**
